<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 5.0.1 setup script
 * Date: Sun, 08 Mar 2020 21:09:06 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'localhost';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';
$cfg['Servers'][$i]['DisableIS'] = true;

/* End of servers configuration */

$cfg['blowfish_secret'] = 'LV/7O8K{YD2}OF>g>l:$f|73ed\'~Z<F';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>